### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [mkotajny/CA5_ColmarAcademy#5]
Overall met expectations.

So I am not sure how much of this project is your friend's influence or what you already did.

The site is really well organized, cleanly put together.

Not sure if the indentation is github or yourself.  I felt that the html was over indented though.

Good organizational practices with comments in your html and css file.

Alt text is important and I wish it was discussed more in our courses.

It is great that you used CSS variables, I like that a lot since it will become more commonly used as time goes on.

Since you just finished off with flexbox I like to mention css grids.
CSS grids is a new positioning feature that works with flexbox.

They will be fully supported by browsers soon.

Take a look at this game and see how far you can get to help prepare you for them.

http://cssgridgarden.com/

Also if you haven't done so already we added css grid as the last section of our css course now.

https://www.codecademy.com/learn/learn-css

Maybe as a final challenge see if you can incorporate it into this site.

**Comment by mkotajny** [comment]
You wrote:
"_So I am not sure how much of this project is your friend's influence or what you already did.__"

My answer:
I have some experience - e.g, 10 years as pro database developer (mostly for Oracle) but zero experience as e.g. front-end developer  :) (I'm learing html, css, bootstrap etc. almost from scratch since 2 months)

Thanks a lot for valuable code review ! :)

Nwo I'm aware of my mistakes (I will add them to my checklist for future projects), but can I leave this (not to fix this issues) and proceed with rest of the training ?
(Will You approve my project anyway ? )

**Comment by mkotajny** [comment]
Fixes implemented in last commit
